runtime: python39
entrypoint: uvicorn app.main:app --host 0.0.0.0 --port $PORT

env_variables:
  IB_HOST: "YOUR_IB_GATEWAY_HOST"
  IB_PORT: "4001"
  IB_CLIENT_ID: "1"

instance_class: F1

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
