order_settings:
  overrides:
    quantity: null
    stop_loss: 40
    take_profit: null
    tp_quantity: null
    trail_amount: 2
    ts_quantity: null
  timeouts:
    bracket_fill: 3600
    fill_or_cancel: 20
  use_take_profit: false
  use_trail_stop: true
